### ISSUE TITLE
Updating module may cause 'Could not load file or assembly...' error - A solution

### ISSUE THREAD

**Issue by kimboslice99** [RvdHout/IIS-GeoIP2block-Module#11]
Just wanted to share some issues I had when I updated

I was getting errors like `This method cannot be called during the application's pre start initialization stage` within IIS Manager and IIS was throwing the following error `Could not load file or assembly 'IISGeoIP2blockModule, Version=2.4.0.0, Culture=neutral, PublicKeyToken=50262f380b75b73d' or one of its dependencies. The system cannot find the file specified.`

The solution is to go to .Net Compilation -> Assemblies, and update the version to match

This was a bit of a head scratcher for me, so I hope this is useful information to others using this module

**Comment by RvdHout** [comment]
You did not download the complete 2.4.0.1 code?
https://github.com/RvdHout/IIS-GeoIP2block-Module/blob/master/Properties/AssemblyInfo.cs says 2.4.0.1

You 'obviously' have to update the installation, eg: gacutil, applicationHost.config and administration.config accordingly... no swapping around dll's

**Comment by kimboslice99** [comment]
Oh yes I did all of this, but still .Net Compilation had 2.4.0.0 in it
