### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by skini82** [RvdHout/IIS-GeoIP2block-Module#4]
Hello, I'm trying to install this module, but when I try to compile it, it tells me JsonProperty and JsonPropertyAttribute were not found.

I tried adding the Newtonsoft.Json module, and it compiled well but it gave me (of course) 2 dlls.
When I try to install on server, it tells me always there are some reference missing.

Any way to compile without 3rd party libraries?
Thanks.
Dario.
![immagine](https://user-images.githubusercontent.com/5445572/97170168-812c7700-178b-11eb-91be-2ae097ead39d.png)

**Comment by RvdHout** [comment]
In my experience Newtonsoft.Json is only required when compiling. I have not included or copied Newtonsoft.Json.dll when installing and it runs without problems.

You correctly followed installation steps in documentation '/docs/Geoblocker - Manual - v2.4.pdf' ?

**Comment by skini82** [comment]
I found the problem: copy/pasting the row for 'applicationHost.config' directly from PDF, the string splits at "Version", placing a space between "Ver" and "sion". Deleting that space, everything started to work.

Sorry for bothering and many thanks for this wonderful module!
Dario

**Comment by RvdHout** [comment]
No problem, enjoy!
